version: 2.1

orbs:
  maven-deploy: wasiqb/maven-deploy@2.1.0
  selenium-orb:
    orbs:
      slack: circleci/slack@3.4.2
    executors:
      selenium-executors:
        docker:
          - image: circleci/openjdk:11-jdk-stretch
          - image: selenium/standalone-chrome:latest
    commands:
      selenium-test:
        steps:
          - attach_workspace:
              at: .
          - run:
              name: Install Chrome
              command: |
                wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
                sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
                sudo apt-get update
                sudo apt-get install google-chrome-stable
          - run:
              name: Run Tests with Sonar Coverage
              command: mvn org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test
          - store_test_results:
              path: target/surefire-reports
          - persist_to_workspace:
              root: .
              paths:
                - .
          - slack/status:
              mentions: mfaisalkhatri,wbhamla1
              webhook: ${SLACK_WEBHOOK}
              fail_only: true
              include_project_field: true
              include_job_number_field: true
              include_visit_job_action: true
    jobs:
      selenium-test:
        executor: selenium-executors
        steps:
          - selenium-test

branches: &all
  only:
    - master
    - release
    - /issue-.*/

workflows:
  workflow:
    jobs:
      - maven-deploy/code-checkout
      - maven-deploy/resolve-dependency:
          requires:
            - maven-deploy/code-checkout
          filters:
            branches:
              <<: *all
      - maven-deploy/build:
          requires:
            - maven-deploy/resolve-dependency
          filters:
            branches:
              <<: *all
      - selenium-orb/selenium-test:
          requires:
            - maven-deploy/build
          filters:
            branches:
              <<: *all
      - maven-deploy/sonar-analysis:
          requires:
            - selenium-orb/selenium-test
          filters:
            branches:
              <<: *all
          context: RELEASE_PROFILE_WASIQB
      - maven-deploy/deploy:
          mentions: mfaisalkhatri,wbhamla1
          fail_only: false
          filters:
            branches:
              only:
                - master
          requires:
            - maven-deploy/sonar-analysis
          context: RELEASE_PROFILE_WASIQB
          deploy-command: mvn deploy --settings settings/settings.xml -DskipTests -Dcheckstyle.skip -B -Prelease
